# Совершенно не ясно почему yaml.
# Не разбирали его, ни ссылок не видел на него...
# Да и в самом стандарте
# https://yaml.org/spec/1.2/spec.html
# описание приведенного примера не нашел
# Например "|--" - что за покемон?
# Непонятно также почему на первом уровне
# продолжается часть этого знака во всех строках
# а на нулевом нет? и на втором и на третьем нет?
# Совершенно непонятно как файлы от папок отличать
# И для чего именно формат yaml, если это вполне
# Я конечно сделаю просто по отступам,
#  ----------------------------------
# |   НО Я АБСОЛЮТНО НЕ ПОНИМАЮ
# |   ДЛЯ ЧЕГО ЗАДАНИЯ СОСТАВЛЕНЫ
# |   ТАКИМ БЕЗДАРНЫМ СПОСОБОМ,
# |   ЧТО ЗАСТАВЛЯЮТ ДЕЛАТЬ КОСТЫЛИ
# |   И ПРИМЕНЯТЬ ПЛОХИЕ ПРАКТИКИ!
#  ----------------------------------
|--my_project
   |--settings
   |  |--__init__.py
   |  |--dev.py
   |  |--prod.py
   |--mainapp
   |  |--__init__.py
   |  |--models.py
   |  |--views.py
   |  |--templates
   |     |--mainapp
   |        |--base.html
   |        |--index.html
   |--authapp
   |  |--__init__.py
   |  |--models.py
   |  |--views.py
   |  |--templates
   |     |--authapp
   |        |--base.html
   |        |--index.html